# Generated by Django 4.1.6 on 2023-10-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='PrimarymeanGrade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='SecondarymeanGrade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='highschoolBiology',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('notDone', 'Not Done')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='highschoolChemistry',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('notDone', 'Not Done')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='highschoolEnglish',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('notDone', 'Not Done')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='highschoolGeography',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('notDone', 'Not Done')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='highschoolMaths',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('notDone', 'Not Done')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='highschoolPhysics',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('notDone', 'Not Done')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='primaryEnglish',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='primaryMaths',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='primaryScience',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10),
        ),
    ]
