# Generated by Django 4.1.6 on 2023-10-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_students_is_admin_alter_students_primarymeangrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
